version: '2'
services:
    foodlogbotadm-app:
        image: foodlogbotadm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://foodlogbotadm-postgresql:5432/foodlogbotadm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    foodlogbotadm-postgresql:
        extends:
            file: postgresql.yml
            service: foodlogbotadm-postgresql
